sink(stderr())
print("test")
system('wget http://cran.r-project.org/src/contrib/Archive/Rcpp/Rcpp_0.10.4.tar.gz')
system('R CMD INSTALL -c Rcpp_0.10.4.tar.gz')
system('rm Rcpp_0.10.4.tar.gz')

install.packages("RODBC",clean=T)
install.packages("Matrix",clean=T)
install.packages("arules",clean=T)
install.packages("ibmdbR",clean=T)
install.packages("dplyr",clean=T)
install.packages("tidyr",clean=T)
install.packages("forcats",clean=T)
install.packages("ggplot2",clean=T)
install.packages("ggmap",clean=T)
install.packages("leaflet",clean=T)
install.packages("DT",clean=T)
install.packages("sp",clean=T)
install.packages("rgdal",clean=T)
install.packages("httr",clean=T)
install.packages("jsonlite",clean=T)
install.packages("shiny",clean=T)


print("All packages installed...")
