# basic options
title: Bikepoint Predictive Modelling Demo
author: Stuart Lynn (GBS Advanced Analytics)
email: stuart.lynn@uk.ibm.com
description: Predictive modelling using open government data, Hive, Python, Spark and the Watson Machine Learning service
#twitter_username: jekyllrb
github_username:  Stuart-Lynn

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
show_downloads: true
gems:
  - jemoji